# Basic Information 
title: Liu Jianmin
position: Master Student
author: Jianmin Liu 
# Ph.D. Student
affiliation: Fujian Normal University
# affiliation_link: https://cs.jhu.edu/
affiliation_logo: https://ccs.fjnu.edu.cn/_upload/tpl/0a/56/2646/template2646/images/logo.png
email: laujianmin@foxmail.com


# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: academic personal homepage, Jianmin Liu, jianmin liu, liujianmin
description: This an academic personal homepage.
canonical: https://laujianmin.github.io/


# The option is used to enable the Johns Hopkins template.
# enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: text #text/icon
google_scholar: https://scholar.google.com/citations?user=zigGlzAAAAAJ&hl=en
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/laujianmin
# linkedin: https://www.linkedin.com/
# twitter: https://twitter.com/

# Images 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote: Copyright Â© 2023 -- by Jianmin Liu.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME

